/* Throwaway / disposable email domains — bundled data, no API call.

   This is the cheap half of spam filtering: a static Set lookup costs nothing and needs no
   third-party service, so it runs before anything that charges per address or touches the
   network. It catches the "give me the PDF, never talk to me again" signups.

   ⚠ THIS LIST IS DELIBERATELY SHORT AND CURATED, NOT EXHAUSTIVE.
   The public blocklists run to ~4,000 domains and go stale in both directions — they carry
   dead domains forever and miss new ones within days. A short list of the services that
   actually generate traffic catches the overwhelming majority for a fraction of the
   maintenance, and the double opt-in step behind it catches what leaks through. Do not treat
   a miss here as a bug; treat a repeat offender in the quarantine log as a reason to add one
   line.

   TO REFRESH: the community list at
   https://github.com/disposable-email-domains/disposable-email-domains
   (disposable_email_blocklist.conf, one domain per line) is the usual source. Merge new
   high-traffic entries in by hand rather than wholesale — importing 4,000 lines would bury
   the ones that matter and makes review impossible.

   Matching is on the registrable domain AND any parent, so `foo.mailinator.com` is caught by
   the `mailinator.com` entry — see subdomain handling in signup-guard.mjs. */

export const DISPOSABLE_DOMAINS = new Set([
  // --- the large, long-running services (most real traffic lands here) ---
  'mailinator.com',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.biz',
  'guerrillamail.de',
  'grr.la',
  'sharklasers.com',
  'spam4.me',
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.co.uk',
  '20minutemail.com',
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  'tempmailo.com',
  'tempmail.plus',
  'tempmailaddress.com',
  'throwawaymail.com',
  'trashmail.com',
  'trashmail.de',
  'trashmail.net',
  'wegwerfmail.de',
  'yopmail.com',
  'yopmail.net',
  'yopmail.fr',
  'cool.fr.nf',
  'jetable.org',
  'nomail.xl.cx',
  'mega.zik.dj',
  'speed.1s.fr',
  'maildrop.cc',
  'mailnesia.com',
  'mailcatch.com',
  'dispostable.com',
  'fakeinbox.com',
  'spamgourmet.com',
  'mytrashmail.com',
  'mailexpire.com',
  'incognitomail.org',
  'getairmail.com',
  'getnada.com',
  'nada.email',
  'inboxkitten.com',
  'emailondeck.com',
  'mohmal.com',
  'linshiyouxiang.net',

  // --- the newer wave (mostly post-2018, high volume) ---
  'moakt.com',
  'moakt.cc',
  'tmail.ws',
  'tmailor.com',
  'minuteinbox.com',
  'mail.tm',
  'mailtm.com',
  'internxt.com',
  'burnermail.io',
  'anonaddy.com',
  'anonaddy.me',
  'mailduck.io',
  'edu.auone.jp',
  'emlhub.com',
  'emlpro.com',
  'emltmp.com',
  'luxusmail.org',
  'vklip.xyz',
  'smailpro.com',
  'tempr.email',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'spambox.us',
  'spambog.com',
  'spamex.com',
  'spamfree24.org',
  'mailsac.com',
  'harakirimail.com',
  'inboxbear.com',
  'tempinbox.com',
  'tempemail.net',
  'tempemails.net',
  'crazymailing.com',
  'clrmail.com',
  'einrot.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'rhyta.com',
  'superrito.com',
  'teleworm.us',
  'armyspy.com',
  'cuvox.de',
  'dayrep.com',

  // --- "alias generator" services (legitimate for privacy, but never worth mailing:
  //     the alias is discarded the moment the first message lands) ---
  'mailinator.net',
  'mailinator.org',
  'sogetthis.com',
  'suremail.info',
  'binkmail.com',
  'bobmail.info',
  'devnullmail.com',
  'letthemeatspam.com',
  'mailin8r.com',
  'notmailinator.com',
  'reallymymail.com',
  'thisisnotmyrealemail.com',
  'tradermail.info',
  'veryrealemail.com',
  'zippymail.info',

  // --- short-lived / redirect domains seen in signup abuse ---
  'byom.de',
  'chammy.info',
  'deadaddress.com',
  'despam.it',
  'disposeamail.com',
  'dodgeit.com',
  'e4ward.com',
  'emailias.com',
  'emailtemporanea.net',
  'emailwarden.com',
  'filzmail.com',
  'front14.org',
  'gishpuppy.com',
  'greensloth.com',
  'ieatspam.eu',
  'imails.info',
  'kasmail.com',
  'killmail.net',
  'klzlk.com',
  'kurzepost.de',
  'lifebyfood.com',
  'lortemail.dk',
  'mail-temporaire.fr',
  'mailbucket.org',
  'maileater.com',
  'mailfreeonline.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnull.com',
  'mailscrap.com',
  'mailshell.com',
  'mailzilla.com',
  'mt2015.com',
  'mvrht.com',
  'myspamless.com',
  'neomailbox.com',
  'nepwk.com',
  'nervmich.net',
  'nervtmich.net',
  'netmails.net',
  'no-spam.ws',
  'nospam4.us',
  'nowmymail.com',
  'objectmail.com',
  'obobbo.com',
  'onewaymail.com',
  'pookmail.com',
  'proxymail.eu',
  'punkass.com',
  'quickinbox.com',
  'rcpt.at',
  'recode.me',
  'recursor.net',
  'rtrtr.com',
  'safetymail.info',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'shieldedmail.com',
  'shortmail.net',
  'sibmail.com',
  'slaskpost.se',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'sofort-mail.de',
  'spam.la',
  'spamavert.com',
  'spamcannon.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamday.com',
  'spamherelots.com',
  'spamhole.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spamobox.com',
  'spamslicer.com',
  'spamspot.com',
  'spamthis.co.uk',
  'spamtroll.net',
  'supergreatmail.com',
  'talkinator.com',
  'teewars.org',
  'tempalias.com',
  'tempe-mail.com',
  'tempomail.fr',
  'temporarily.de',
  'temporaryemail.net',
  'temporaryinbox.com',
  'thankyou2010.com',
  'trash-amil.com',
  'trash2009.com',
  'trashdevil.com',
  'trashymail.com',
  'tyldd.com',
  'uggsrock.com',
  'wh4f.org',
  'whyspam.me',
  'willselfdestruct.com',
  'wuzup.net',
  'wuzupmail.net',
  'xoxy.net',
  'yepmail.net',
  'zoemail.org',
]);

/* Local parts that are never a person signing up for a retirement newsletter.

   Kept SMALL on purpose. `info@`, `contact@` and `sales@` are omitted even though they are
   role addresses, because a self-employed reader genuinely may use one — and the double
   opt-in behind this will filter them anyway if nobody is there. Only addresses that cannot
   receive human attention at all belong here. */
export const NON_HUMAN_LOCALPARTS = new Set([
  'noreply',
  'no-reply',
  'donotreply',
  'do-not-reply',
  'postmaster',
  'mailer-daemon',
  'mailerdaemon',
  'abuse',
  'bounce',
  'bounces',
  'nobody',
  'devnull',
  'null',
  'root',
]);
