#!/usr/bin/env python3
"""Propagate the shared header + footer partials into the hand-maintained root pages.

The marketing site is static (Vercel, no server-side includes), so the shared chrome
is baked into each page at build time. Edit `partials/header.html` or
`partials/footer.html`, then run this script to push the change to every root page.
The blog pages get the same partials via `tools/blog_build.py`.

Each root page keeps its own <head> (title, meta, inline analytics) and <main>
content. This script only rewrites the two shared regions:
    <header class="site-header"> ... </header>
    <footer class="site-footer"> ... </footer>
It is idempotent: after a run the regions equal the partials, so running again is a
no-op. The header's {{CUR_*}} nav tokens are filled per page so the active nav item
gets aria-current="page".

Run from anywhere:  python Website/tools/page_build.py
Verify only:        python Website/tools/page_build.py --check

--check writes nothing and exits 1 if any page's chrome no longer matches the partials.
It covers the blog pages too, because they share the same partials via blog_build.py —
so it catches the one silent failure of baking chrome in: editing a partial and
forgetting to propagate. `sync.ps1` runs it before every Website push.
"""

import re
import sys
from pathlib import Path

WEBSITE = Path(__file__).resolve().parents[1]
PARTIALS = WEBSITE / "partials"

# root page filename -> header nav key to mark current ("" = not in the nav)
PAGES = {
    "index.html": "HOME",
    "products.html": "PRODUCTS",
    "features.html": "FEATURES",
    "how-it-works.html": "HOW",
    "getting-started.html": "START",
    "sessions.html": "SESSIONS",
    "technical.html": "",
    "updates.html": "",
    "faq.html": "FAQ",
    "contact.html": "",
    "affiliates.html": "",
    "privacy.html": "",
    "terms.html": "",
    "newsletter.html": "",
    "demo.html": "",
    "about.html": "",
    "thanks.html": "",
    "404.html": "",
}

NAV_KEYS = ["HOME", "PRODUCTS", "FEATURES", "HOW", "START", "SESSIONS", "BLOG", "FAQ"]

HEADER_RE = re.compile(r'<header class="site-header">.*?</header>', re.S)
FOOTER_RE = re.compile(r'<footer class="site-footer">.*?</footer>', re.S)


def header_for(active):
    h = (PARTIALS / "header.html").read_text(encoding="utf-8").strip()
    for k in NAV_KEYS:
        h = h.replace("{{CUR_%s}}" % k,
                      ' aria-current="page"' if k == active else "")
    return h


def drift_in(path, active, footer):
    """Which shared regions of `path` no longer match the partials. [] = in sync.

    Read-only. Used by --check to catch the one real weakness of baking the chrome in:
    editing a partial and forgetting to propagate it, which fails silently.
    """
    html = path.read_text(encoding="utf-8")
    out = []
    h, f = HEADER_RE.search(html), FOOTER_RE.search(html)
    if not h or h.group(0) != header_for(active):
        out.append("header")
    if not f or f.group(0) != footer:
        out.append("footer")
    return out


def check():
    """Verify every generated page still matches the partials. Exit 1 on drift.

    Covers BOTH consumers: the root pages (rebuilt by this script) and the blog pages
    (rebuilt by blog_build.py), since a partial edit invalidates both.
    """
    footer = (PARTIALS / "footer.html").read_text(encoding="utf-8").strip()
    stale_root, stale_blog = [], []

    for name, active in PAGES.items():
        f = WEBSITE / name
        if not f.exists():
            sys.exit("page_build --check: missing page %s" % name)
        d = drift_in(f, active, footer)
        if d:
            stale_root.append("%s (%s)" % (name, "+".join(d)))

    # Blog landing + posts are generated by blog_build.py but share the same partials.
    blog_pages = [WEBSITE / "blog.html"] + sorted((WEBSITE / "blog").glob("*.html"))
    for f in blog_pages:
        if not f.exists():
            continue
        d = drift_in(f, "BLOG", footer)
        if d:
            stale_blog.append("%s (%s)" % (f.name, "+".join(d)))

    total = len(PAGES) + len(blog_pages)
    if not stale_root and not stale_blog:
        print("page_build --check: OK — %d page(s) match the partials." % total)
        return 0

    print("page_build --check: STALE CHROME — a partial was edited but not propagated.\n")
    if stale_root:
        print("  %d root page(s) out of sync:" % len(stale_root))
        for s in stale_root[:10]:
            print("    - %s" % s)
        if len(stale_root) > 10:
            print("    ... and %d more" % (len(stale_root) - 10))
        print("    fix: python Website/tools/page_build.py\n")
    if stale_blog:
        print("  %d blog page(s) out of sync:" % len(stale_blog))
        for s in stale_blog[:10]:
            print("    - %s" % s)
        if len(stale_blog) > 10:
            print("    ... and %d more" % (len(stale_blog) - 10))
        print("    fix: python Website/tools/blog_build.py\n")
    return 1


def main():
    if "--check" in sys.argv:
        sys.exit(check())
    footer = (PARTIALS / "footer.html").read_text(encoding="utf-8").strip()
    changed = 0
    for name, active in PAGES.items():
        f = WEBSITE / name
        if not f.exists():
            sys.exit("page_build: missing page %s" % name)
        html = f.read_text(encoding="utf-8")
        if not HEADER_RE.search(html):
            sys.exit('page_build: no <header class="site-header"> in %s' % name)
        if not FOOTER_RE.search(html):
            sys.exit('page_build: no <footer class="site-footer"> in %s' % name)
        new = HEADER_RE.sub(lambda m: header_for(active), html, count=1)
        new = FOOTER_RE.sub(lambda m: footer, new, count=1)
        if new != html:
            f.write_text(new, encoding="utf-8")
            changed += 1
            print("  updated: %s (nav=%s)" % (name, active or "-"))
        else:
            print("  unchanged: %s" % name)
    print("Done. %d of %d page(s) updated." % (changed, len(PAGES)))
    if changed:
        print("NOTE: blog pages share these partials — run "
              "`python Website/tools/blog_build.py` too if a partial changed.")


if __name__ == "__main__":
    main()
