"""Render approved customer quotes into index.html.

Reads Website/data/testimonials.json and rewrites the region between
<!-- TESTIMONIALS:START --> and <!-- TESTIMONIALS:END --> in index.html. Same
idempotent marked-region approach page_build.py uses for the shared header and footer,
and for the same reason: the published HTML stays a build artifact of a data file, so
what is on the site cannot drift away from what was actually approved.

    python Website/tools/testimonials_build.py            # write the region
    python Website/tools/testimonials_build.py --check    # exit 1 if it has drifted
    python Website/tools/testimonials_build.py --data X   # render from a scratch file

--data exists so the renderer can be exercised without ever putting invented quotes in
data/testimonials.json. That file is the published record; writing fake entries into it,
even for a moment, is exactly what Plans/Testimonials-Pipeline.md forbids.

WHY THE MINIMUM: below three quotes the section renders as nothing at all. One or two
testimonials read as thin and invite "is this even real?", which costs more trust than it
buys. That was a written rule that nobody could enforce; here it is a condition in code.

WHAT THIS DELIBERATELY DOES NOT EMIT: star ratings, an average score, or Review /
AggregateRating structured data. An aggregate implies the quotes are representative of all
customers, which curated testimonials are not — and Google has excluded self-collected
reviews about your own products from star rich results since 2019, so there is no upside
to weigh against that.

Every record here must have reached `approved` through api/feedback-approve.mjs. This
script is a renderer, not a gate: it trusts the data file, and the data file is only ever
written by `tools/admin/cli.mjs publish`, which does check.
"""

import html
import json
import re
import sys
from pathlib import Path

WEBSITE = Path(__file__).resolve().parents[1]
INDEX = WEBSITE / "index.html"
DEFAULT_DATA = WEBSITE / "data" / "testimonials.json"

MIN_TO_PUBLISH = 3

START = "<!-- TESTIMONIALS:START -->"
END = "<!-- TESTIMONIALS:END -->"
REGION_RE = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)

EMPTY_NOTE = (
    "  {start}\n"
    "  <!-- No section rendered: fewer than {n} approved quotes. This is not a bug —\n"
    "       see Website/tools/testimonials_build.py. -->\n"
    "  {end}"
)


def esc(s):
    return html.escape(str(s if s is not None else ""), quote=True)


def render(records):
    """The HTML for the marked region. Empty-but-explained below the minimum."""
    approved = [r for r in records if r.get("text") and r.get("attribution")]
    if len(approved) < MIN_TO_PUBLISH:
        return EMPTY_NOTE.format(start=START, n=MIN_TO_PUBLISH, end=END)

    cards = []
    for r in approved:
        build = r.get("app_build")
        # The build a quote was written about. Shown quietly, because the planner changes
        # and a reader deserves to know which version someone was describing.
        meta = (
            '\n            <p class="tm-meta">On planner v%s</p>' % esc(build)
            if build
            else ""
        )
        cards.append(
            "          <figure class=\"tm-card\">\n"
            "            <blockquote class=\"tm-quote\">%s</blockquote>\n"
            "            <figcaption class=\"tm-attrib\">%s</figcaption>%s\n"
            "          </figure>"
            % (esc(r["text"]), esc(r["attribution"]), meta)
        )

    return (
        "%s\n"
        "  <!-- Generated by Website/tools/testimonials_build.py — do not hand-edit. -->\n"
        "  <section class=\"section\">\n"
        "    <div class=\"container\">\n"
        "      <div class=\"center\" style=\"max-width:55ch;margin-inline:auto;margin-bottom:2.4rem;\">\n"
        "        <span class=\"eyebrow\" style=\"justify-content:center;\">In their words</span>\n"
        "        <h2>What buyers say</h2>\n"
        "        <p class=\"lead center\">A small number of customers, quoted with their permission and in their own\n"
        "        words. Nothing was offered in exchange, and each of them approved the exact wording below.</p>\n"
        "      </div>\n"
        "      <div class=\"tm-grid\">\n"
        "%s\n"
        "      </div>\n"
        "    </div>\n"
        "  </section>\n"
        "  %s" % (START, "\n".join(cards), END)
    )


def load(data_path):
    if not data_path.exists():
        return []
    raw = json.loads(data_path.read_text(encoding="utf-8") or "[]")
    if not isinstance(raw, list):
        raise SystemExit("%s must contain a JSON array" % data_path)
    return raw


def main(argv):
    check = "--check" in argv
    data_path = DEFAULT_DATA
    if "--data" in argv:
        data_path = Path(argv[argv.index("--data") + 1]).resolve()

    records = load(data_path)
    wanted = render(records)

    src = INDEX.read_text(encoding="utf-8")
    if not REGION_RE.search(src):
        print("ERROR: %s has no %s / %s markers." % (INDEX.name, START, END))
        print("       Restore them or the approved quotes can never be rendered.")
        return 1

    current = REGION_RE.search(src).group(0)
    # Compare on the region only, ignoring the indentation the replacement re-establishes.
    if current.strip() == wanted.strip():
        n = len([r for r in records if r.get("text")])
        print("testimonials_build: OK — region matches (%d approved quote(s), minimum %d)."
              % (n, MIN_TO_PUBLISH))
        return 0

    if check:
        print("testimonials_build --check: index.html no longer matches data/testimonials.json.")
        print("       Run: python Website/tools/testimonials_build.py")
        return 1

    INDEX.write_text(REGION_RE.sub(lambda _: wanted, src, count=1), encoding="utf-8")
    n = len([r for r in records if r.get("text")])
    if n < MIN_TO_PUBLISH:
        print("testimonials_build: region cleared — %d approved quote(s), need %d to publish."
              % (n, MIN_TO_PUBLISH))
    else:
        print("testimonials_build: rendered %d quote(s) into index.html." % n)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
